### ISSUE TITLE
Theme Adjustment

### ISSUE THREAD

**Issue by pcox3** [AndroidPoet/CountryPicker#3]
<img width="375" alt="Screenshot 2024-09-15 at 6 29 24 AM" src="https://github.com/user-attachments/assets/938dc503-52bd-407d-ba81-b58e150b9520">

It will be great to apply background on the container and not the listItem. That way, theme color is applied to the searchBar area as well the as the overall background.

**Comment by AndroidPoet** [comment]
Dynamic layout has been added and you can now chnage background theme
